project: lib_device_control
version: 5.0.0

## example of overridable setting
# watermarks is redefined in documentation and again for a specific product
# eg different products might have different setting but we'd like to provide defaults
watermarks: []

products:
  lib_device_control:
    documentation:
      build_path: doc/_build
      output_path: doc/_out

documentation:
  title: Device Control Library
  root_doc: doc/index.rst
  exclude_patterns_path: doc/exclude_patterns.inc
  substitutions_path: doc/substitutions.inc
  pdfs:
    doc/index:
      pdf_title: '{{product}} - User Guide'
      pdf_filename: '{{product}}__user_guide_v{{version}}'
